services:
  caddy:
    image: caddy:2
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nostalgia
    depends_on:
      - web
      - api
    restart: unless-stopped

  postgres:
    image: groonga/pgroonga:3.2.3-alpine-16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=nostalgia
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - nostalgia
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - nostalgia
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nostalgia
    volumes:
      - ./resources:/app/resources
    environment:
      - DB_SOURCE=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/nostalgia?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
    restart: unless-stopped

  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    volumes:
      - ./resources:/usr/share/nginx/resources
      - ./logs/nginx:/var/log/nginx
    networks:
      - nostalgia
    depends_on:
      - api
    restart: unless-stopped

volumes:
  data-volume:
  caddy_data:
  caddy_config:

networks:
  nostalgia:
    driver: bridge